In [1]:
import numpy as np
import pandas as pd
pd.options.display.max_rows = 10
np.set_printoptions(precision=4, suppress=True)

In [19]:
df = pd.read_csv('reviews.csv')
cleaned_df = df.dropna().reset_index(drop=True)
cleaned_df

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted,DateModified
0,2,992,2008,gayg msft,5,better than any you can get at a restaurant!,2000-01-25T21:44:00Z,2000-01-25T21:44:00Z
1,7,4384,1634,Bill Hilbrich,4,"I cut back on the mayo, and made up the differ...",2001-10-17T16:49:59Z,2001-10-17T16:49:59Z
2,9,4523,2046,Gay Gilmore ckpt,2,i think i did something wrong because i could ...,2000-02-25T09:00:00Z,2000-02-25T09:00:00Z
3,13,7435,1773,Malarkey Test,5,easily the best i have ever had. juicy flavor...,2000-03-13T21:15:00Z,2000-03-13T21:15:00Z
4,14,44,2085,Tony Small,5,An excellent dish.,2000-03-28T12:51:00Z,2000-03-28T12:51:00Z
...,...,...,...,...,...,...,...,...
1401763,2090339,139499,2002080368,terrylbiggs,2,I was disappointed. I couldn't wait to make th...,2020-12-27T23:57:54Z,2020-12-27T23:57:54Z
1401764,2090340,148484,41805321,rogerberry,5,Nothing to drain. And I don’t heat up the liqu...,2020-12-28T00:44:42Z,2020-12-28T00:44:42Z
1401765,2090341,264191,2002901848,Reiketsukan 6.,5,Good base recipe for someone to start with. I ...,2020-12-28T01:04:43Z,2020-12-28T01:04:43Z
1401766,2090345,411791,2002901938,Sue M.,5,Thank you so much for this amazing recipe! I l...,2020-12-28T03:07:10Z,2020-12-28T03:07:10Z
1401767,2090347,352686,2002812127,dede25cory,5,I can't say enough about this recipe.... the b...,2020-12-28T03:23:48Z,2020-12-28T03:23:48Z

In [23]:
cleaned_df.groupby('Rating')['Review'].count()

Rating
0      76248
1      16555
2      17596
3      50276
4     229181
5    1011912
Name: Review, dtype: int64

In [31]:
balanced_df = cleaned_df.groupby('Rating', group_keys=False).apply(lambda x: x.sample(n=16000, random_state=55))

balanced_df.to_csv("balanced_reviews.csv", index=False)

C:\Users\awanh\AppData\Local\Temp\ipykernel_32092\656355737.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_df = cleaned_df.groupby('Rating', group_keys=False).apply(lambda x: x.sample(n=16000, random_state=55))

In [33]:
new_df = pd.read_csv('balanced_reviews.csv')
new_df

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted,DateModified
0,1163076,42738,1728091,frosty1961,0,This was very good but I added 1/2 a cup of sh...,2010-11-12T14:38:46Z,2010-11-12T14:38:46Z
1,187623,129556,90324,Tarra1,0,We call this ABC Dip almonds bacon and cheese....,2005-07-13T10:05:25Z,2005-07-13T10:05:25Z
2,1343062,208146,2465854,jarvisg,0,I made this for an office potluck; threw it to...,2012-10-24T16:41:50Z,2012-10-24T16:41:50Z
3,538267,49769,64642,Molly53,0,I have this very same recipe in an old cookboo...,2007-12-20T21:10:59Z,2007-12-20T21:10:59Z
4,1174163,169929,679953,weekend cooker,0,Great cookies! !! Made recipe as posted with n...,2010-12-20T17:56:14Z,2010-12-20T17:56:14Z
...,...,...,...,...,...,...,...,...
95995,1427035,268418,114197,Dave of Tucson,5,The seasoning is the best that I have tried! T...,2014-01-24T16:17:08Z,2014-01-24T16:17:08Z
95996,988862,145591,7676,Dr. Paul,5,Great Recipe. I'm living in a guest house in K...,2009-11-14T12:15:27Z,2009-11-14T12:15:27Z
95997,489331,118821,513848,memaw 2,5,delicious,2007-10-01T16:33:20Z,2007-10-01T16:33:20Z
95998,317323,128343,130819,Gerry,5,We love crunchy when it comes to perogies and ...,2006-09-28T16:10:03Z,2006-09-28T16:10:03Z
95999,797636,44669,711249,Andiidee,5,This was very good. I used a homemade pie cru...,2009-01-26T19:19:16Z,2009-01-26T19:19:16Z

In [35]:
new_df.groupby('Rating')['Review'].count()

Rating
0    16000
1    16000
2    16000
3    16000
4    16000
5    16000
Name: Review, dtype: int64